name: Discord Git Webhook 

on:
  push:
    branches:
      - main  # change to your branch if needed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
