name: Discord Git Webhook 

on:
  push:
    branches:
      - main  # change to your branch if needed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: discord-webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
